backend:
  name: github
  repo: infinit-luffy/notes   # ← 修改为你的仓库
  branch: main
  # 使用 GitHub OAuth 需要一个代理（Edge Function/Serverless）。
  # 将 base_url 指向你的 OAuth 代理域名，并确保该域名在 GitHub OAuth App 的回调白名单中。
  # 参考: https://decapcms.org/docs/backends-overview/
  base_url: https://<your-oauth-proxy-domain>   # ← 替换为你部署 OAuth 代理的域名
  auth_endpoint: /api/auth

media_folder: "docs/assets/uploads"     # 文件实际存放路径（仓库内）
public_folder: "/assets/uploads"        # 站点访问路径

local_backend: false

site_url: https://infinit-luffy.github.io/notes/

publish_mode: editorial_workflow

collections:
  - name: "notes"
    label: "笔记（Markdown）"
    folder: "docs/notes"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "notes/{{slug}}/"
    media_folder: "docs/assets/uploads"
    public_folder: "/assets/uploads"
    fields:
      - { label: 标题, name: title, widget: string }
      - { label: 日期, name: date, widget: datetime }
      - { label: 标签, name: tags, widget: list, required: false }
      - { label: 正文, name: body, widget: markdown }

  # 方式 A：在 Markdown 内直接写原生 HTML（MkDocs 支持），适合“HTML 片段”
  # 方式 B：需要完整 .html 文件时，建议通过 GitHub 网页上传到 docs/html/ 目录
  # 若你确需在后台直接创建 .html 文件，可以另行定制小工具或使用代码小组件。